### PR TITLE
Fix for #94 (private IP querying)

### PR DESCRIPTION
**Pull request by jeannustre**
Changes from https://github.com/DataDog/dd-sdk-ios/pull/830

Also added 'GENERATE_INFOPLIST_FILE = YES;' to Tests target in order for tests to run.

### CODE REVIEW

**Comment by Reflejo** [comment]
I’d recommend we put it behind some configuration flag since there are
legit cases where you’d want to use Kronos with a local ntpd

Just out of curiosity what domain are you querying when you get local area
IPs?

**Comment by jeannustre** [comment]
I'm getting the system prompt asking for local network access with the default configuration, using `Clock.sync()` with no parameters, so that would be time.apple.com only.

**Comment by Reflejo** [comment]
If I understand correctly, you are saying your DNS resolves time.apple.com
to a local area IP? What’s your network setup? What DNS are you using?
Would be nice if we can debug a bit more your use case.

**Comment by jeannustre** [comment]
My use case is the same as issue #94 : in an iOS app, using just `Clock.sync()` seems to trigger a system pop-up requesting access to the local network under certain conditions.

I have had it happen some time ago on my device but did not take note of my network configuration, sorry. I have been receiving user reports about it but did not reproduce it myself since.

Reading up more on [DataDog's repo](https://github.com/DataDog/dd-sdk-ios/issues/647), I see that their fix I made a PR with is not working entirely on their end, sadly. But they have investigated the matter a lot more than I, maybe the issue there will be interesting to you.

**Comment by zettlunic** [comment]
Hi folks, we're seeing similar reports from our users. Seems to happen on mobile networks mostly. 
Apple Developer forums has a good post summarizing what could cause this prompt to be shown, besides connecting to a local IP. https://developer.apple.com/forums/thread/663874

Is there anything in there that you could match to operations done with `Clock.sync()`?

**Comment by zettlunic** [comment]
Hey folks! We're seeing similar reports from our users. What came to my mind is that time.apple.com might be resolved to something weird (cached?) for certain networks or mobile data providers. Anyways, we'll run a fork including this fix + using a different NTP host. I can update here if this reduces the occurrences of hitting the local network prompt. 

Cheers!

**Comment by jeannustre** [comment]
Hi @zettlunic, did this seem to help ? We are also considering using another NTP host (pool.ntp.org) to see if the issue still occurs.

**Comment by Reflejo** [comment]
It's still totally possible to get to this situation if the NTP server for some reason resolves to a private ip range. Like a local gateway serving as a dnsd can do that. Some wifi networks do that for redirecting to a landing, etc.

**Comment by zettlunic** [comment]
> Hi @zettlunic, did this seem to help ? We are also considering using another NTP host (pool.ntp.org) to see if the issue still occurs.

@jeannustre unfortunately it did not. Even resolving pool.ntp.org lead to the prompt. See https://developer.apple.com/forums/thread/709691 for more details, I've also filed a feedback report (FB12047743) which hasn't been responded to.

**Comment by Reflejo** [comment]
As I mentioned before. I can definitely see how this happens. This is how it can happen:

- You connect to a WiFi network
- Through DHCP you get assigned dns IPs to a local gateway (say 192.168.1.1)
- While resolving pool.ntp.org, the gateway points to 192.168.1.1
  - This could happen either because it's running an ntp server or more likely because you are on a guest network and it's trying to present you with a login wall

I guess a way this could be solved is to have a `defaultNTPIPWhenOnLocalLAN` sort of fallback?

**Pull request closed without merging**
